import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  {
    // `next-env.d.ts` is generated by Next on every build and is gitignored; `design/`
    // holds the read-only design-canvas source pulled from Claude Design.
    ignores: [".next/**", "out/**", "node_modules/**", "design/**", "next-env.d.ts"],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default config;
